services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: SecretManager
      MYSQL_USER: secretmanager
      MYSQL_PASSWORD: setuser
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    container_name: node-webserver
    environment:
      DATABASE_URL: mysql://secretmanager:setuser@mysql:3306/SecretManager
    ports:
      - "80:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
