CREATE DATABASE IF NOT EXISTS SecretManager;
FLUSH PRIVILEGES;

USE SecretManager;

CREATE TABLE IF NOT EXISTS Secret (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    data VARCHAR(255) NOT NULL,
    expiry DATETIME NOT NULL
);
